using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HermesService.Domain.Entity.SICLONET
{
      public partial class Entregas : Entregas_cte_filiais_x_remetente
    {
           public Entregas()
           {
                //Buffer_filiais_x_remetente = new HashSet<Entregas_cte_filiais_x_remetente>();
           }
        public int Id_fila { get; set; }
        public int STATUS { get; set; }
           public int Rtnc { get; set; }
           public string Acao { get; set; }
           public decimal Advalorem { get; set; }
           public int Agencia { get; set; }
           public decimal Aliq_icms { get; set; }
           public decimal Altura { get; set; }
           public string Ar_reprogramada { get; set; }
           public string Area { get; set; }
           public bool Arquivo_enviado_correio { get; set; }
           public int Arquivo_gerado { get; set; }
           public int Arquivo_retorno_bmk   { get; set; }
           public bool Auditoria_encomenda   { get; set; }
           public string Autor_observacao { get; set; }
           public string Bairro_Dest { get; set; }
           public bool Baixou_estoque { get; set; }
           public decimal Base_calc_icms { get; set; }
           public decimal Basetx { get; set; }
           public decimal Basetxadvalorem { get; set; }
           public decimal Basetxar { get; set; }
           public string Canal { get; set; }
           public string Categoria { get; set; }
           public string Categoria_marketing   { get; set; }
           public string Cc { get; set; }
           public string Celular { get; set; }
           public string Celular2 { get; set; }
           public string Cenario { get; set; }
           public string Cep_Dest { get; set; }
           public string Cep_origem   { get; set; }
           public string Chave_cte_siclo { get; set; }
           public string Chave_nfe_cliente { get; set; }
           public string Cidade_Dest { get; set; }
           public int Clientecodigo  { get; set; }
           public string Cnpj_Dest { get; set; }
           public char Cobrado_cliente { get; set; }
           public int Codarquivo   { get; set; }
           public int Codarquivo_env_cliente { get; set; }
           public int Codarquivoretorno { get; set; }
           public string Codbarradev   { get; set; }
           public string Codbase { get; set; }
           public string Codbaseatual  { get; set; }
           public string Codbaseenvio  { get; set; }
           public string Codbaseenvioreal { get; set; }
           public string Codbaseexec   { get; set; }
           public string Codcanal { get; set; }
           public int Codcheque { get; set; }
           public int Codcidade { get; set; }
           public int Codcliente   { get; set; }
           public string Coddestinatario { get; set; }
           public string Codembossadora { get; set; }
           public string Codentrega   { get; set; }
           public string Codentrega_arquivo   { get; set; }
           public string Codentregacli  { get; set; }
           public string Codentregacorreio { get; set; }
           public int Codentregador  { get; set; }
           public int Codgrupoproduto { get; set; }
           public string Codigo_local  { get; set; }
           public string Codigoproduto  { get; set; }
           public int Codkit { get; set; }
           public string Codleitor { get; set; }
           public int Codlista_imagem { get; set; }
           public int Codlsita_codbo { get; set; }
           public int Codmotivodevol { get; set; }
           public string Codmun_Dest { get; set; }
           public int Codprocedimento { get; set; }
           public int Codproduto   { get; set; }
           public string Codproduto_troca { get; set; }
           public int Codsituacao   { get; set; }
           public int Codsituacaoatual { get; set; }
           public int Codtipolista  { get; set; }
           public int Codusuario   { get; set; }
           public bool Com_ar { get; set; }
           public string Compartilhado  { get; set; }
           public string Complemento_Dest   { get; set; }
           public decimal Comprimento   { get; set; }
           public string Contato { get; set; }
           public string Contato2 { get; set; }
           public string Contato3 { get; set; }
           public string Contrato { get; set; }
           public string Controle { get; set; }
           public string Cpf_cnpj { get; set; }
           public string Cte_cliente_serie { get; set; }
           public string Cte_serie_siclo { get; set; }
           public DateTime? Data_alteracao { get; set; }
           public DateTime? Data_atendimento { get; set; }
           public DateTime? Data_baixa   { get; set; }
           public DateTime? Data_cadastro  { get; set; }
           public DateTime? Data_chamado  { get; set; }
           public DateTime? Data_coleta   { get; set; }
           public DateTime? Data_coleta_externo   { get; set; }
           public DateTime? Data_coleta_ponta { get; set; }
           public DateTime? Data_despacho  { get; set; }
           public DateTime? Data_download_imagem  { get; set; }
           public DateTime? Data_entrega  { get; set; }
           public DateTime? Data_entrega_nova { get; set; }
           public DateTime? Data_envio   { get; set; }
           public DateTime? Data_expedicao_matriz  { get; set; }
           public DateTime? Data_fechamento { get; set; }
           public DateTime? Data_follow   { get; set; }
           public DateTime? Data_geracao  { get; set; }
           public DateTime? Data_limite   { get; set; }
           public DateTime? Data_lista_entrega   { get; set; }
           public DateTime? Data_movimento { get; set; }
           public DateTime Data_nota_fiscal { get; set; }
           public DateTime? Data_observacao { get; set; }
           public DateTime? Data_pedido   { get; set; }
           public DateTime? Data_pesagem  { get; set; }
           public DateTime? Data_pgto_parceiro   { get; set; }
           public DateTime? Data_precoleta { get; set; }
           public DateTime? Data_recebido_cliente  { get; set; }
           public DateTime? Data_ult_tentativa   { get; set; }
           public DateTime? Data_webserver_correios { get; set; }
           public DateTime? Datapesagem   { get; set; }
           public string Ddd  { get; set; }
           public string Ddd1 { get; set; }
           public string Dentro_fora { get; set; }
           public string Dentro_fora_ima_dev { get; set; }
           public string Desc_evento_esp   { get; set; }
           public string Descricao { get; set; }
           public string Descricao_projeto  { get; set; }
           public string Destinatario { get; set; }
           public int Devolucao_posterior   { get; set; }
           public int Dias { get; set; }
           public int Dias_fraude   { get; set; }
           public int Dias_uteis_gastos { get; set; }
           public string Documento { get; set; }
           public string Email { get; set; }
           public bool Emite_protocolo { get; set; }
           public string Empresa { get; set; }
           public string End_referencia { get; set; }
           public string Endereco { get; set; }
           public bool Entra_fraude  { get; set; }
           public bool Entrega_capital { get; set; }
           public string Entrega_estado { get; set; }
           public string Entrega_fct   { get; set; }
           public string Entrega_particularidade { get; set; }
           public string Entrega_pos   { get; set; }
           public string Entrega_pv   { get; set; }
           public bool Enviado_cte   { get; set; }
           public string Estado { get; set; }
           public string Estado_ori   { get; set; }
           public string Evento { get; set; }
           public DateTime? Evento_data   { get; set; }
           public DateTime? Evento_Data_termino   { get; set; }
           public string Evento_descricao { get; set; }
           public string Fantasia { get; set; }
           public bool Faturado_cliente { get; set; }
           public string Fct { get; set; }
           public string Filiacao { get; set; }
           public string Filial { get; set; }
           public int Finalizado   { get; set; }
           public string Forma_ar { get; set; }
           public bool Gera_faturamento { get; set; }
           public string Habilitacao   { get; set; }
           public string Header { get; set; }
           public bool  Imagem_enviada { get; set; }
           public char? Incice_icms   { get; set; }
           public string Insc_est { get; set; }
           public string Instrucao1   { get; set; }
           public string Instrucao2   { get; set; }
           public string Instrucao3   { get; set; }
           public decimal Largura { get; set; }
           public decimal Latitude { get; set; }
           public bool Libera_retorno { get; set; }
           public char Lida { get; set; }
           public decimal Longitude { get; set; }
           public string Lote { get; set; }
           public int Lote_baixa   { get; set; }
           public bool Mao_propria   { get; set; }
           public string Modelo_equipamento   { get; set; }
           public string Momento_log   { get; set; }
           public string Nome_equipamento { get; set; }
           public string Nome_mao_propria { get; set; }
           public string Nrnota { get; set; }
           public string Nro_bo { get; set; }
           public string Num_cheque   { get; set; }
           public string Num_cheque_final { get; set; }
           public string Num_cheque_inicial   { get; set; }
           public int Num_folhas   { get; set; }
           public string Num_pab { get; set; }
           public string Numero { get; set; }
           public string Numero_cte_cliente   { get; set; }
           public string Numero_cte_siclo { get; set; }
           public string Observacao   { get; set; }
           public string Operacao { get; set; }
           public decimal Outro_valor   { get; set; }
           public bool Pagto_parceiro { get; set; }
           public string Pedido { get; set; }
           public decimal Peso { get; set; }
           public decimal Peso_antigo   { get; set; }
           public decimal Peso_balanca  { get; set; }
           public decimal Peso_cubado   { get; set; }
           public string Plaqueta1 { get; set; }
           public string Plaqueta2 { get; set; }
           public int Prazo { get; set; }
           public int Prazo_entregar { get; set; }
           public string Prioridade   { get; set; }
           public string Problema { get; set; }
           public string Projeto { get; set; }
           public string Protocolo_bo  { get; set; }
           public string Pv { get; set; }
           public int Qtd_acess { get; set; }
           public int Qtd_aparelho  { get; set; }
           public int Qtd_cartao   { get; set; }
           public decimal Qtd_mat_prom  { get; set; }
           public decimal Qtd_notebook  { get; set; }
           public int Qtd_sac { get; set; }
           public int Qtd_talao { get; set; }
           public decimal Qtd_tim_chip  { get; set; }
           public int Quantidade   { get; set; }
           public int Quantidade4   { get; set; }
           public string Ramal { get; set; }
           public string Ramal1 { get; set; }
           public string Ramal2 { get; set; }
           public string Ramo { get; set; }
           public bool Recebido_cte  { get; set; }
           public int Reprogramada  { get; set; }
           public string Seguencial   { get; set; }
           public bool Seguro { get; set; }
           public string Select { get; set; }
           public bool Select_private { get; set; }
           public int Sequencial   { get; set; }
           public string Serie { get; set; }
           public string Serie_equipamento { get; set; }
           public string Setor_na_empresa1 { get; set; }
           public string Setor_na_empresa2 { get; set; }
           public string Setor_na_empresa3 { get; set; }
           public char Sitevisit { get; set; }
           public string Situacao { get; set; }
           public string Status_cliente { get; set; }
           public string Stringworkday  { get; set; }
           public bool Auspeita_fraude { get; set; }
           public string Tecnico { get; set; }
           public string Tecnico_telefone { get; set; }
           public int  Tecnino_nome  { get; set; }
           public string Telefone { get; set; }
           public string Telefone1 { get; set; }
           public string Telefone2 { get; set; }
           public bool Telemarketing  { get; set; }
           public int Tentativas   { get; set; }
           public string Terminal { get; set; }
           public string Terminal_troca { get; set; }
           public string Tipo { get; set; }
           public char Tipo_baixa   { get; set; }
           public string Tipo_evento   { get; set; }
           public char Tipo_lote { get; set; }
           public char Tipo_pessoa   { get; set; }
           public char Tipo_transporte_carga  { get; set; }
           public decimal Txmanuseio   { get; set; }
           public string Unitx { get; set; }
           public decimal Unitxadvalorem { get; set; }
           public decimal Unitxar { get; set; }
           public decimal Valor_correio  { get; set; }
           public decimal Valor_uniex   { get; set; }
           public decimal Valordeclarado { get; set; }
           public decimal Vlr_acess { get; set; }
           public decimal Vlr_adicional  { get; set; }
           public decimal Vlr_aparelho  { get; set; }
           public decimal Vlr_ar_mao_propria   { get; set; }
           public decimal Vlr_cartao   { get; set; }
           public decimal Vlr_despacho  { get; set; }
           public decimal Vlr_entrega   { get; set; }
           public decimal Vlr_faturado  { get; set; }
           public decimal Vlr_gris { get; set; }
           public decimal Vlr_icms { get; set; }
           public decimal Vlr_icms_retido { get; set; }
           public decimal Vlr_icms_retirdo { get; set; }
           public decimal Vlr_iss { get; set; }
           public decimal Vlr_mao_propria { get; set; }
           public decimal Vlr_mat_prom  { get; set; }
           public decimal Vlr_notebook  { get; set; }
           public decimal Vlr_rec_elet  { get; set; }
           public decimal Vlr_seguro   { get; set; }
           public decimal Vlr_tim_chip  { get; set; }
           public decimal Vlr_total_frete { get; set; }
    
    
    
            //public virtual ICollection<Entregas_cte_filiais_x_remetente> Buffer_filiais_x_remetente { get; set; }
    
      }
}
